import subprocess
import sys
from today import get_previous_day_range

def run_app():
    """
    Run app.py with the date range generated by get_previous_day_range.
    """
    try:
        # Get the date range from get_previous_day_range
        from_date, to_date = get_previous_day_range()

        # Construct the command to run app.py with the date range as arguments
        command = [sys.executable, "process_insights.py", from_date, to_date]

        # Execute the command
        result = subprocess.run(command, capture_output=True, text=True)

        # Output the result
        if result.returncode == 0:
            print("app.py executed successfully:\n")
            print(result.stdout)
        else:
            print("app.py execution failed:\n")
            print(result.stderr)

    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    run_app()
